
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep 30 2025 07:23:00 PKT (Sep 30 2025 02:23:00 UTC)

// Verification Directory fv/counter 

// module counter(clk, reset, count);
//   input clk, reset;
//   output [3:0] count;
//   wire clk, reset;
//   wire [3:0] count;
//   wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
//   DFCNQD1 \count_reg[3] (.CDN (n_6), .CP (clk), .D (n_5), .Q
//        (count[3]));
//   DFCNQD1 \count_reg[2] (.CDN (n_6), .CP (clk), .D (n_3), .Q
//        (count[2]));
//   MOAI22D1 g81__2398(.A1 (n_4), .A2 (count[3]), .B1 (n_4), .B2
//        (count[3]), .ZN (n_5));
//   DFCNQD1 \count_reg[1] (.CDN (n_6), .CP (clk), .D (n_1), .Q
//        (count[1]));
//   OA21D1 g83__5107(.A1 (n_2), .A2 (count[2]), .B (n_4), .Z (n_3));
//   ND2D1 g85__6260(.A1 (n_2), .A2 (count[2]), .ZN (n_4));
//   IAO21D1 g86__4319(.A1 (count[0]), .A2 (count[1]), .B (n_2), .ZN
//        (n_1));
//   AN2XD1 g88__8428(.A1 (count[0]), .A2 (count[1]), .Z (n_2));
//   CKND0 g89(.I (reset), .ZN (n_6));
//   DFCND1 \count_reg[0] (.CDN (n_6), .CP (clk), .D (n_0), .Q (count[0]),
//        .QN (n_0));
// endmodule


// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep 30 2025 08:31:23 PKT (Sep 30 2025 03:31:23 UTC)

// Verification Directory fv/counter 

module counter(clk, reset, count, SE, scan_in, scan_out);
  input clk, reset, SE, scan_in;
  output [3:0] count;
  output scan_out;
  wire clk, reset, SE, scan_in;
  wire [3:0] count;
  wire scan_out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  assign scan_out = count[3];
  SDFCNQD1 \count_reg[3] (.CDN (n_6), .CP (clk), .D (n_5), .SI
       (count[2]), .SE (SE), .Q (count[3]));
  SDFCNQD1 \count_reg[2] (.CDN (n_6), .CP (clk), .D (n_3), .SI
       (count[1]), .SE (SE), .Q (count[2]));
  SDFCNQD1 \count_reg[1] (.CDN (n_6), .CP (clk), .D (n_1), .SI
       (count[0]), .SE (SE), .Q (count[1]));
  MOAI22D1 g81__2398(.A1 (n_4), .A2 (count[3]), .B1 (n_4), .B2
       (count[3]), .ZN (n_5));
  OA21D1 g83__5107(.A1 (n_2), .A2 (count[2]), .B (n_4), .Z (n_3));
  SDFCNQD1 \count_reg[0] (.CDN (n_6), .CP (clk), .D (n_0), .SI
       (scan_in), .SE (SE), .Q (count[0]));
  ND2D1 g85__6260(.A1 (n_2), .A2 (count[2]), .ZN (n_4));
  IAO21D1 g86__4319(.A1 (count[1]), .A2 (count[0]), .B (n_2), .ZN
       (n_1));
  AN2XD1 g88__8428(.A1 (count[1]), .A2 (count[0]), .Z (n_2));
  CKND0 g90(.I (count[0]), .ZN (n_0));
  CKND0 g89(.I (reset), .ZN (n_6));
endmodule


// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Oct  1 2025 05:08:12 PKT (Oct  1 2025 00:08:12 UTC)

// Verification Directory fv/counter 

module counter(clk, reset, count, SE, scan_in, scan_out);
  input clk, reset, SE, scan_in;
  output [3:0] count;
  output scan_out;
  wire clk, reset, SE, scan_in;
  wire [3:0] count;
  wire scan_out;
  wire n_2, n_4, n_6, n_7, n_9, n_11, n_14;
  assign scan_out = count[3];
  SDFCNQD1 \count_reg[3] (.CDN (n_11), .CP (clk), .D (n_14), .SI
       (count[2]), .SE (SE), .Q (count[3]));
  SDFCNQD1 \count_reg[2] (.CDN (n_11), .CP (clk), .D (n_7), .SI
       (count[1]), .SE (SE), .Q (count[2]));
  SDFCNQD1 \count_reg[1] (.CDN (n_11), .CP (clk), .D (n_4), .SI
       (count[0]), .SE (SE), .Q (count[1]));
  OA21D1 g83__5107(.A1 (n_6), .A2 (count[2]), .B (n_9), .Z (n_7));
  SDFCNQD1 \count_reg[0] (.CDN (n_11), .CP (clk), .D (n_2), .SI
       (scan_in), .SE (SE), .Q (count[0]));
  ND2D1 g85__6260(.A1 (n_6), .A2 (count[2]), .ZN (n_9));
  IAO21D1 g86__4319(.A1 (count[1]), .A2 (count[0]), .B (n_6), .ZN
       (n_4));
  AN2XD1 g88__8428(.A1 (count[1]), .A2 (count[0]), .Z (n_6));
  CKND0 g93(.I (count[0]), .ZN (n_2));
  CKND0 g92(.I (reset), .ZN (n_11));
  XNR2D1 g2(.A1 (n_9), .A2 (count[3]), .ZN (n_14));
endmodule

