
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep 30 2025 07:23:00 PKT (Sep 30 2025 02:23:00 UTC)

// Verification Directory fv/counter 

// module counter(clk, reset, count);
//   input clk, reset;
//   output [3:0] count;
//   wire clk, reset;
//   wire [3:0] count;
//   wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
//   DFCNQD1 \count_reg[3] (.CDN (n_6), .CP (clk), .D (n_5), .Q
//        (count[3]));
//   DFCNQD1 \count_reg[2] (.CDN (n_6), .CP (clk), .D (n_3), .Q
//        (count[2]));
//   MOAI22D1 g81__2398(.A1 (n_4), .A2 (count[3]), .B1 (n_4), .B2
//        (count[3]), .ZN (n_5));
//   DFCNQD1 \count_reg[1] (.CDN (n_6), .CP (clk), .D (n_1), .Q
//        (count[1]));
//   OA21D1 g83__5107(.A1 (n_2), .A2 (count[2]), .B (n_4), .Z (n_3));
//   ND2D1 g85__6260(.A1 (n_2), .A2 (count[2]), .ZN (n_4));
//   IAO21D1 g86__4319(.A1 (count[0]), .A2 (count[1]), .B (n_2), .ZN
//        (n_1));
//   AN2XD1 g88__8428(.A1 (count[0]), .A2 (count[1]), .Z (n_2));
//   CKND0 g89(.I (reset), .ZN (n_6));
//   DFCND1 \count_reg[0] (.CDN (n_6), .CP (clk), .D (n_0), .Q (count[0]),
//        .QN (n_0));
// endmodule


// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Sep 30 2025 08:31:23 PKT (Sep 30 2025 03:31:23 UTC)

// Verification Directory fv/counter 

// module counter(clk, reset, count, SE, scan_in, scan_out);
//   input clk, reset, SE, scan_in;
//   output [3:0] count;
//   output scan_out;
//   wire clk, reset, SE, scan_in;
//   wire [3:0] count;
//   wire scan_out;
//   wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
//   assign scan_out = count[3];
//   SDFCNQD1 \count_reg[3] (.CDN (n_6), .CP (clk), .D (n_5), .SI
//        (count[2]), .SE (SE), .Q (count[3]));
//   SDFCNQD1 \count_reg[2] (.CDN (n_6), .CP (clk), .D (n_3), .SI
//        (count[1]), .SE (SE), .Q (count[2]));
//   SDFCNQD1 \count_reg[1] (.CDN (n_6), .CP (clk), .D (n_1), .SI
//        (count[0]), .SE (SE), .Q (count[1]));
//   MOAI22D1 g81__2398(.A1 (n_4), .A2 (count[3]), .B1 (n_4), .B2
//        (count[3]), .ZN (n_5));
//   OA21D1 g83__5107(.A1 (n_2), .A2 (count[2]), .B (n_4), .Z (n_3));
//   SDFCNQD1 \count_reg[0] (.CDN (n_6), .CP (clk), .D (n_0), .SI
//        (scan_in), .SE (SE), .Q (count[0]));
//   ND2D1 g85__6260(.A1 (n_2), .A2 (count[2]), .ZN (n_4));
//   IAO21D1 g86__4319(.A1 (count[1]), .A2 (count[0]), .B (n_2), .ZN
//        (n_1));
//   AN2XD1 g88__8428(.A1 (count[1]), .A2 (count[0]), .Z (n_2));
//   CKND0 g90(.I (count[0]), .ZN (n_0));
//   CKND0 g89(.I (reset), .ZN (n_6));
// endmodule


// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Oct  4 2025 03:38:19 PKT (Oct  3 2025 22:38:19 UTC)

// Verification Directory fv/counter 

// module counter(clk, reset, count);
//   input clk, reset;
//   output [3:0] count;
//   wire clk, reset;
//   wire [3:0] count;
//   wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
//   DFCNQD1 \count_reg[3] (.CDN (n_6), .CP (clk), .D (n_5), .Q
//        (count[3]));
//   DFCNQD1 \count_reg[2] (.CDN (n_6), .CP (clk), .D (n_3), .Q
//        (count[2]));
//   MOAI22D1 g81__2398(.A1 (n_4), .A2 (count[3]), .B1 (n_4), .B2
//        (count[3]), .ZN (n_5));
//   DFCNQD1 \count_reg[1] (.CDN (n_6), .CP (clk), .D (n_1), .Q
//        (count[1]));
//   OA21D1 g83__5107(.A1 (n_2), .A2 (count[2]), .B (n_4), .Z (n_3));
//   ND2D1 g85__6260(.A1 (n_2), .A2 (count[2]), .ZN (n_4));
//   IAO21D1 g86__4319(.A1 (count[0]), .A2 (count[1]), .B (n_2), .ZN
//        (n_1));
//   AN2XD1 g88__8428(.A1 (count[0]), .A2 (count[1]), .Z (n_2));
//   CKND0 g89(.I (reset), .ZN (n_6));
//   DFCND1 \count_reg[0] (.CDN (n_6), .CP (clk), .D (n_0), .Q (count[0]),
//        .QN (n_0));
// endmodule


// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Oct  4 2025 23:16:10 PKT (Oct  4 2025 18:16:10 UTC)

// Verification Directory fv/counter 

// module counter(clk, reset, count);
//   input clk, reset;
//   output [3:0] count;
//   wire clk, reset;
//   wire [3:0] count;
//   wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
//   SDFCNQD1 \count_reg[3] (.CDN (n_6), .CP (clk), .D (n_0), .SI
//        (count[3]), .SE (n_5), .Q (count[3]));
//   SDFCNQD1 \count_reg[2] (.CDN (n_6), .CP (clk), .D (n_3), .SI
//        (count[2]), .SE (n_4), .Q (count[2]));
//   SDFCNQD1 \count_reg[1] (.CDN (n_6), .CP (clk), .D (count[1]), .SI
//        (n_1), .SE (count[0]), .Q (count[1]));
//   OR2XD1 g83__2398(.A1 (n_4), .A2 (n_3), .Z (n_5));
//   ND2D1 g85__5107(.A1 (count[0]), .A2 (count[1]), .ZN (n_4));
//   INVD0 g87(.I (count[1]), .ZN (n_1));
//   INVD0 g86(.I (count[3]), .ZN (n_0));
//   CKND1 g88(.I (count[2]), .ZN (n_3));
//   CKND0 g89(.I (reset), .ZN (n_6));
//   DFCND1 \count_reg[0] (.CDN (n_6), .CP (clk), .D (n_2), .Q (count[0]),
//        .QN (n_2));
// endmodule


// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Oct  5 2025 05:10:18 PKT (Oct  5 2025 00:10:18 UTC)

// Verification Directory fv/counter 

module counter(clk, reset, count, SE, scan_in, scan_out);
  input clk, reset, SE, scan_in;
  output [3:0] count;
  output scan_out;
  wire clk, reset, SE, scan_in;
  wire [3:0] count;
  wire scan_out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  assign scan_out = count[3];
  SDFCNQD1 \count_reg[3] (.CDN (n_6), .CP (clk), .D (n_5), .SI
       (count[2]), .SE (SE), .Q (count[3]));
  SDFCNQD1 \count_reg[2] (.CDN (n_6), .CP (clk), .D (n_3), .SI
       (count[1]), .SE (SE), .Q (count[2]));
  SDFCNQD1 \count_reg[1] (.CDN (n_6), .CP (clk), .D (n_1), .SI
       (count[0]), .SE (SE), .Q (count[1]));
  MOAI22D1 g81__2398(.A1 (n_4), .A2 (count[3]), .B1 (n_4), .B2
       (count[3]), .ZN (n_5));
  OA21D1 g83__5107(.A1 (n_2), .A2 (count[2]), .B (n_4), .Z (n_3));
  SDFCNQD1 \count_reg[0] (.CDN (n_6), .CP (clk), .D (n_0), .SI
       (scan_in), .SE (SE), .Q (count[0]));
  CKND2D1 g85__6260(.A1 (n_2), .A2 (count[2]), .ZN (n_4));
  IAO21D1 g86__4319(.A1 (count[1]), .A2 (count[0]), .B (n_2), .ZN
       (n_1));
  AN2XD1 g88__8428(.A1 (count[1]), .A2 (count[0]), .Z (n_2));
  INVD0 g90(.I (count[0]), .ZN (n_0));
  CKND0 g89(.I (reset), .ZN (n_6));
endmodule

